# Generated by Django 5.1 on 2024-08-31 12:50

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_detail',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='news_datetime_published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='news_image',
            field=models.ImageField(upload_to='static/images/topics/'),
        ),
    ]
