# Generated by Django 5.1 on 2024-09-16 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_news_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('PAKISTAN', 'Pakistan'), ('BUSINESS', 'Business'), ('INTERNATIONAL', 'International'), ('SPORTS', 'Sports')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
