# Generated by Django 5.1 on 2024-09-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsarticle_slug'),
    ]

    operations = [
    ]
