# Generated by Django 5.1 on 2024-09-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_newsarticle_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
