# Generated by Django 5.0.9 on 2024-09-21 11:50

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsarticle_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='news_image',
            field=models.ImageField(upload_to=news.models.unique_image_path),
        ),
    ]
